# .github/workflows/bandit-scan.yml
name: Bandit Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Bandit Scan
        uses: shundor/bandit-action@v1
        with:
          path: "."                # Scan the entire repository
          level: "high"           # Report only HIGH severity issues
          confidence: "high"      # Report only HIGH confidence issues
          exit_zero: "true"       # Exit with 0 even if issues are found
          skips: "B101,B301"      # Skip specific tests
          excluded_paths: ".svn,CVS,.bzr,.hg,.git,__pycache__,.tox,*.egg"
          ini_path: ".github/bandit.yml"  # Path to your custom config file (if not using .bandit)