name: Python Bandit Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    name: Run Bandit Python Code Scan
    steps:
      - uses: actions/checkout@v2  # Checks out the code
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Set Python version
      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Run Bandit scan
        uses: shundor/bandit-action@v1
        with:
          path: "."            # Scan the current directory
          level: high          # Focus on high-severity issues
          confidence: high     # Only report issues with high confidence
          exit_zero: true      # Allow the action to exit successfully even if issues are found
